FROM alpine:latest

RUN apk add --no-cache ca-certificates git openssh-client bash

COPY ./maumirror /usr/bin/maumirror

VOLUME /data
VOLUME /config
EXPOSE 29321

RUN adduser --disabled-password -u 29321 maumirror
USER 29321:29321

CMD ["/usr/bin/maumirror", "-c", "/config/config.json"]
