FROM alpine:latest

RUN apk add --no-cache ca-certificates

COPY ./maumirror /usr/bin/maumirror

VOLUME /data
VOLUME /config
EXPOSE 29321
USER 1337:1337

CMD ["/usr/bin/maumirror", "-c", "/config/config.json"]
