FROM alpine:latest

RUN apk add --no-cache ca-certificates bash

COPY ./maumirror /usr/bin/maumirror

VOLUME /data
VOLUME /config
EXPOSE 29321
USER 29321:29321

CMD ["/usr/bin/maumirror", "-c", "/config/config.json"]
